### ISSUE TITLE
Support for modrinth?

### ISSUE THREAD

**Issue by EagyOnGithub** [maruohon/malilib#155] opened 2024-06-16 23:28 UTC
(Sorry if I'm doing this wrong I don't use github regularly) MaLiLib is on Modrinth but it doesn't seem supported. If it isn't inconvenient it would be nice to have mods like tweakeroo, minihub etc. on Modrinth as well as Curseforge.

**Comment by NatoBoram** [comment] 2024-06-17 16:42
> (Sorry if I'm doing this wrong I don't use github regularly) 

On GitHub, the first thing you should do is *search* for the issue you want to create.

* https://github.com/maruohon/malilib/issues?q=modrinth

Here, you can see that the same thing was asked now thrice. So this issue is a duplicate.

* Duplicate of #36

Once you found your issue, you can click the <kbd>:+1:</kbd> icon on it and click on the <kbd>:bell: Subscribe</kbd> button in that issue. This way, you'll receive a GitHub notification when there'll be another activity in that issue. Not only that, but we can see that there's 17 people who're interested in this.

**Closed as completed** 2024-06-17 19:25 UTC
